- Importing numpy library using import statement


In [2]:
import numpy as np


In [3]:
a  = np.array([1, 2, 3, 4, 5])
b  = np.array([6,7,8,9])

print(a, b)

[1 2 3 4 5] [6 7 8 9]


In [5]:
print(a+b)
print(a-b)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [6]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])  # Adjusted the length of array b to match array a

print("Array a:", a)
print("Array b:", b)

print("a + b:", a + b)
print("a - b:", a - b)

Array a: [1 2 3 4 5]
Array b: [ 6  7  8  9 10]
a + b: [ 7  9 11 13 15]
a - b: [-5 -5 -5 -5 -5]


In [7]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [9]:
a3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(a3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
print(a3.shape) #2, 2, 2 mmeans 2X2X2 matrices
print(a3.ndim) #3 means 3D array
print(a3.dtype) #int32 means 32 bit integer

(2, 2, 2)
3
int32


In [ ]:
np.arange(10) #array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [13]:
np.arange(1,20) 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [14]:
np.arange(1,20,2) #array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [15]:
np.random.randint(1,11)

2

In [16]:
np.random.randint(1,11,size=(2,3))

array([[3, 6, 8],
       [4, 5, 4]])

In [17]:
x = np.array([[7,2,3],
             [2,3,5],
             [4,3,6]])

y = np.array([[5,7,8],
              [4,3,2],
              [8,1,2]])

print(x)
print(y)

[[7 2 3]
 [2 3 5]
 [4 3 6]]
[[5 7 8]
 [4 3 2]
 [8 1 2]]


In [18]:
print(x+y)

[[12  9 11]
 [ 6  6  7]
 [12  4  8]]


- Matrix Multiplication

In [ ]:
print(x@y) #matrix multiplication(1st Method)

[[67 58 66]
 [62 28 32]
 [80 43 50]]


In [ ]:
np.dot(x,y) #2nd Method (same as x@y)

In [21]:
print(x)
x.prod() #product of all elements of x

[[7 2 3]
 [2 3 5]
 [4 3 6]]


90720

In [22]:
x.mean() #mean of all elements of x

3.888888888888889

In [ ]:
x.mean(axis=0) #mean of all elements of x row wise

array([4.33333333, 2.66666667, 4.66666667])

In [24]:
x.mean(axis=1) #mean of all elements of x column wise

array([4.        , 3.33333333, 4.33333333])

In [25]:
print(x.sum())
print(x.std())
print(x.var())
print(x.min())

35
1.6629588385661962
2.7654320987654324
2


- to find the percentile of the array or collection of same elements

In [26]:
a = np.array([1,2,3,4,5])
print(np.percentile(a, 50)) #50th percentile
print(np.percentile(a, 25)) #25th percentile
print(np.percentile(a, 75)) #75th percentile

3.0
2.0
4.0


- If we have a 3X3 size of matrix, and now we have to reshape in 2X2 then we use reshape() method

In [30]:
print(y.reshape(1,9)) #reshaping 3X3 matrix to 1X9 matrix

[[5 7 8 4 3 2 8 1 2]]


In [29]:
print(y.reshape(9,1)) #reshaping 3X3 matrix to 9X1 matrix

[[5]
 [7]
 [8]
 [4]
 [3]
 [2]
 [8]
 [1]
 [2]]


In [31]:
print(x)

[[7 2 3]
 [2 3 5]
 [4 3 6]]


In [33]:
print(x[0]) #1st row

[7 2 3]


In [34]:
print(x[0][0]) #1st element of 1st row

7


In [ ]:
print(x[1][1])  #2nd element of 2nd row

3


In [36]:
print(x[-1])  #last row

[4 3 6]


In [37]:
print(x[-1][0]) #1st element of last row

4
